/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.grup32.ui;

import com.vektorel.grup32.ui.mdi.FrmMDIOrnek;

/**
 *
 * @author vektorel
 */
public class FrmAnasayfa extends javax.swing.JFrame {

    /**
     * Creates new form FrmAnasayfa
     */
    public FrmAnasayfa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnIslemler = new javax.swing.JMenu();
        mnMDIOrnek = new javax.swing.JMenuItem();
        mItemKisi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnIslemler.setText("İşlemler");

        mnMDIOrnek.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnMDIOrnek.setText("MDI Örnek");
        mnMDIOrnek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMDIOrnekActionPerformed(evt);
            }
        });
        mnIslemler.add(mnMDIOrnek);

        mItemKisi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mItemKisi.setText("Kişi İşlemleri");
        mItemKisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemKisiActionPerformed(evt);
            }
        });
        mnIslemler.add(mItemKisi);

        jMenuBar1.add(mnIslemler);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnMDIOrnekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMDIOrnekActionPerformed
       FrmMDIOrnek frmMDIOrnek=new FrmMDIOrnek();
       frmMDIOrnek.setVisible(true);
    }//GEN-LAST:event_mnMDIOrnekActionPerformed

    private void mItemKisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemKisiActionPerformed
        FrmKisiListe fkl =new FrmKisiListe();
        fkl.setVisible(true);
    }//GEN-LAST:event_mItemKisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mItemKisi;
    private javax.swing.JMenu mnIslemler;
    private javax.swing.JMenuItem mnMDIOrnek;
    // End of variables declaration//GEN-END:variables
}
