/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.grup32.ui;

import com.vektorel.grup32.kalitim.Kisiler;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class FrmKisiListe extends javax.swing.JFrame {

    /**
     * Creates new form FrmKisiListe
     */
    public FrmKisiListe() {
        initComponents();
        Kisiler kisiler =new Kisiler();
        kisiler.listeyiYukle();
        kisiListele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKisi = new javax.swing.JTable();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        btnYeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKisi);

        btnSil.setText("Sil");

        btnGuncelle.setText("Güncelle");

        btnYeni.setText("Yeni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnYeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuncelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSil)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(btnGuncelle)
                    .addComponent(btnYeni)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnYeni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKisi;
    // End of variables declaration//GEN-END:variables

    private void kisiListele() {
        String[] columnNames = new String[4];
        columnNames[0] = "Kişi No";
        columnNames[1] = "Adı";
        columnNames[2] = "Soyadı";
        columnNames[3] = "Doğum Tarihi";

        String[][] data = new String[Kisiler.kisiListesi.size()][4];

        for (int i = 0; i < Kisiler.kisiListesi.size(); i++) {
            data[i][0] = Kisiler.kisiListesi.get(i).getNo().toString();
            data[i][1] = Kisiler.kisiListesi.get(i).getAd();
            data[i][2] = Kisiler.kisiListesi.get(i).getSoyad();
            data[i][3] = Kisiler.kisiListesi.get(i).getDogumTarihi().toLocaleString();
        }

        tblKisi.setModel(new DefaultTableModel(data, columnNames));
    }
}
