/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.grup32.ui;

import com.vektorel.grup32.kalitim.Kisi;
import com.vektorel.grup32.kalitim.Kisiler;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class FrmKisiListe extends javax.swing.JFrame {

    Kisiler kisiler =new Kisiler();
    /**
     * Creates new form FrmKisiListe
     */
    public FrmKisiListe() {
        initComponents();
        kisiler.listeyiYukle();
        kisiListele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKisi = new javax.swing.JTable();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        btnYeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblKisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKisi);

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        btnYeni.setText("Yeni");
        btnYeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnYeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuncelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSil)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSil)
                    .addComponent(btnGuncelle)
                    .addComponent(btnYeni)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      kisiler.listeyiYedekle();
    }//GEN-LAST:event_formWindowClosing

    private void btnYeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYeniActionPerformed
        DlgKisi dk=new DlgKisi(this, true);
        dk.setVisible(true);
        kisiListele();
    }//GEN-LAST:event_btnYeniActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        int selectedRowIndex = tblKisi.getSelectedRow();
        if(selectedRowIndex!=-1){
            Kisi kisi = Kisiler.kisiListesi.get(selectedRowIndex);
            int yesNoResult = JOptionPane.showConfirmDialog(this, kisi.getNo() + " numaralı kişiyi silmek ");
            if(yesNoResult==0){
                 Kisiler.kisiListesi.remove(selectedRowIndex);
                 kisiListele();
            }
        }
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
         int selectedRowIndex = tblKisi.getSelectedRow();
        if(selectedRowIndex!=-1){
            Kisi kisi = Kisiler.kisiListesi.get(selectedRowIndex);
            DlgKisi dk=new DlgKisi(this, true,kisi,selectedRowIndex);
            dk.setVisible(true);
            kisiListele();
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnYeni;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKisi;
    // End of variables declaration//GEN-END:variables

    private void kisiListele() {
        String[] columnNames = new String[4];
        columnNames[0] = "Kişi No";
        columnNames[1] = "Adı";
        columnNames[2] = "Soyadı";
        columnNames[3] = "Doğum Tarihi";

        String[][] data = new String[Kisiler.kisiListesi.size()][4];

        for (int i = 0; i < Kisiler.kisiListesi.size(); i++) {
            data[i][0] = Kisiler.kisiListesi.get(i).getNo().toString();
            data[i][1] = Kisiler.kisiListesi.get(i).getAd();
            data[i][2] = Kisiler.kisiListesi.get(i).getSoyad();
            data[i][3] = Kisiler.kisiListesi.get(i).getDogumTarihi().toLocaleString();
        }

        tblKisi.setModel(new DefaultTableModel(data, columnNames));
    }
}
